services:
  postgres:
    image: postgres:latest
    container_name: votacao_postgres
    environment:
      POSTGRES_DB: votacao_db
      POSTGRES_USER: votacao_user
      POSTGRES_PASSWORD: votacao_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U votacao_user -d votacao_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  app:
    build: .
    container_name: votacao_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/votacao_db
      SPRING_DATASOURCE_USERNAME: votacao_user
      SPRING_DATASOURCE_PASSWORD: votacao_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  influxdb:
    image: influxdb:1.8
    container_name: votacao_influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - influxdb_data:/var/lib/influxdb
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: votacao_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    restart: always

  k6:
    image: grafana/k6:latest
    container_name: votacao_k6
    volumes:
      - ./k6:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    depends_on:
      - influxdb
      - app

volumes:
  postgres_data:
  influxdb_data:
  grafana_data: